//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceDetaliExtras
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalii", Namespace="http://schemas.datacontract.org/2004/07/P1", IsReference=true)]
    public partial class Detalii : object
    {
        
        private System.Nullable<System.DateTime> DataField;
        
        private bool DeletedField;
        
        private string EvenimentField;
        
        private System.Collections.Generic.List<ServiceReferenceDetaliExtras.Extras> ExtrasField;
        
        private int IdField;
        
        private string LocatieField;
        
        private string PathField;
        
        private string PeisajeField;
        
        private string PersoaneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eveniment
        {
            get
            {
                return this.EvenimentField;
            }
            set
            {
                this.EvenimentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDetaliExtras.Extras> Extras
        {
            get
            {
                return this.ExtrasField;
            }
            set
            {
                this.ExtrasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locatie
        {
            get
            {
                return this.LocatieField;
            }
            set
            {
                this.LocatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Peisaje
        {
            get
            {
                return this.PeisajeField;
            }
            set
            {
                this.PeisajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Persoane
        {
            get
            {
                return this.PersoaneField;
            }
            set
            {
                this.PersoaneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Extras", Namespace="http://schemas.datacontract.org/2004/07/P1", IsReference=true)]
    public partial class Extras : object
    {
        
        private ServiceReferenceDetaliExtras.Detalii DetaliiField;
        
        private int DetaliiIdField;
        
        private int IdField;
        
        private string NumeField;
        
        private string ValoareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDetaliExtras.Detalii Detalii
        {
            get
            {
                return this.DetaliiField;
            }
            set
            {
                this.DetaliiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliiId
        {
            get
            {
                return this.DetaliiIdField;
            }
            set
            {
                this.DetaliiIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valoare
        {
            get
            {
                return this.ValoareField;
            }
            set
            {
                this.ValoareField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDetaliExtras.IDetaliiExtras")]
    public interface IDetaliiExtras
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/getDetalii", ReplyAction="http://tempuri.org/InterfaceDetalii/getDetaliiResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDetaliExtras.Detalii> getDetaliiAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/addDetalii", ReplyAction="http://tempuri.org/InterfaceDetalii/addDetaliiResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDetaliExtras.Detalii> addDetaliiAsync(ServiceReferenceDetaliExtras.Detalii d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/getAllDetalii", ReplyAction="http://tempuri.org/InterfaceDetalii/getAllDetaliiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceDetaliExtras.Detalii>> getAllDetaliiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/UpdateDetalii", ReplyAction="http://tempuri.org/InterfaceDetalii/UpdateDetaliiResponse")]
        System.Threading.Tasks.Task UpdateDetaliiAsync(ServiceReferenceDetaliExtras.Detalii d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/Save", ReplyAction="http://tempuri.org/InterfaceDetalii/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetalii/Dispose", ReplyAction="http://tempuri.org/InterfaceDetalii/DisposeResponse")]
        System.Threading.Tasks.Task DisposeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceExtras/AddExtras", ReplyAction="http://tempuri.org/InterfaceExtras/AddExtrasResponse")]
        System.Threading.Tasks.Task AddExtrasAsync(ServiceReferenceDetaliExtras.Detalii d, ServiceReferenceDetaliExtras.Extras extra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDetaliiExtrasChannel : ServiceReferenceDetaliExtras.IDetaliiExtras, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DetaliiExtrasClient : System.ServiceModel.ClientBase<ServiceReferenceDetaliExtras.IDetaliiExtras>, ServiceReferenceDetaliExtras.IDetaliiExtras
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DetaliiExtrasClient() : 
                base(DetaliiExtrasClient.GetDefaultBinding(), DetaliiExtrasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDetaliiExtras.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DetaliiExtrasClient(EndpointConfiguration endpointConfiguration) : 
                base(DetaliiExtrasClient.GetBindingForEndpoint(endpointConfiguration), DetaliiExtrasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DetaliiExtrasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DetaliiExtrasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DetaliiExtrasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DetaliiExtrasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DetaliiExtrasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDetaliExtras.Detalii> getDetaliiAsync(string path)
        {
            return base.Channel.getDetaliiAsync(path);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDetaliExtras.Detalii> addDetaliiAsync(ServiceReferenceDetaliExtras.Detalii d)
        {
            return base.Channel.addDetaliiAsync(d);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceDetaliExtras.Detalii>> getAllDetaliiAsync()
        {
            return base.Channel.getAllDetaliiAsync();
        }
        
        public System.Threading.Tasks.Task UpdateDetaliiAsync(ServiceReferenceDetaliExtras.Detalii d)
        {
            return base.Channel.UpdateDetaliiAsync(d);
        }
        
        public System.Threading.Tasks.Task SaveAsync()
        {
            return base.Channel.SaveAsync();
        }
        
        public System.Threading.Tasks.Task DisposeAsync()
        {
            return base.Channel.DisposeAsync();
        }
        
        public System.Threading.Tasks.Task AddExtrasAsync(ServiceReferenceDetaliExtras.Detalii d, ServiceReferenceDetaliExtras.Extras extra)
        {
            return base.Channel.AddExtrasAsync(d, extra);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDetaliiExtras))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDetaliiExtras))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DetaliiExtrasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDetaliiExtras);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DetaliiExtrasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDetaliiExtras);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDetaliiExtras,
        }
    }
}
