//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extras
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Valoare { get; set; }
        public int DetaliiId { get; set; }
    
        public virtual Detalii Detalii { get; set; }
    }
}
